<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Manjuus-Mac.local" failures="1" tests="1" name="Default test" time="21.769" errors="0" timestamp="10 Dec 2020 14:44:02 GMT">
  <testcase classname="uiAutomation.TestDriverClasses" name="FirstScript" time="18.377">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.xframium.page.factory.DefaultPageFactory.invoke(DefaultPageFactory.java:157)
at com.sun.proxy.$Proxy24.LogOut(Unknown Source)
at pages.spi.PageImplInvoker.LogOut(PageImplInvoker.java:27)
at uiAutomation.TestDriverClasses.FirstScript(TestDriverClasses.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: null
at org.xframium.page.element.AbstractElement.click(AbstractElement.java:647)
at org.xframium.page.element.AbstractElement.click(AbstractElement.java:613)
at functions.GenericFunctions._click(GenericFunctions.java:335)
at pages.spi.LoginImpl.LogOut(LoginImpl.java:99)
... 23 more
]]>
    </failure>
  </testcase> <!-- FirstScript -->
</testsuite> <!-- Default test -->
